import { build } from 'esbuild'
import assert from 'node:assert/strict'
import { writeFile, unlink } from 'node:fs/promises'
const mock = `export const supabase=globalThis.__libraryMock;`
const result=await build({stdin:{contents:`export * from './src/lib/saves';export * from './src/lib/journal';export * from './src/lib/exportData';export * from './src/lib/account';export * from './src/lib/posts';`,resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'mock',setup(b){b.onResolve({filter:/supabase$/},()=>({path:'mock',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:mock}))}}]})
let book={revision:1,settings:{profile:{displayName:'Keep'},other:'keep'},records:[{collection:'lists',id:'same',payload:{title:'Shopping',items:[{id:'milk',text:'Milk',done:false,custom:42}],unknown:{keep:true}}},{collection:'notes',id:'same',payload:{title:'Note',body:'hello',color:3}}]}
let failSync=false,failTable=false, calls=[]
globalThis.__libraryMock={auth:{getSession:async()=>({data:{session:{user:{id:'owner'}}}}),getUser:async()=>({data:{user:{id:'owner'}}})},rpc:async(name,args)=>{calls.push(name);if(name==='daybook_load')return {data:structuredClone(book)};if(failSync)return {error:new Error('conflict')};assert.equal(args.expected,book.revision);for(const c of args.changes){const i=book.records.findIndex(r=>r.collection===c.collection&&r.id===c.id);if(c.deleted){if(i>=0)book.records.splice(i,1)}else if(i<0)book.records.push(c);else book.records[i]=c}book.settings=args.preferences;book.revision++;return {data:book.revision}},from:()=>({select(){return this},order(){return this},async range(a,b){if(failTable)return {error:new Error('offline')};return {data:Array.from({length:1201},(_,id)=>({id})).slice(a,b+1)}}})}
const file=new URL('./.library-test-bundle.mjs',import.meta.url);await writeFile(file,result.outputFiles[0].text)
try{const lib=await import(file.href+'?'+Date.now());
const saves=await lib.listSaves();assert.equal(new Set(saves.map(x=>x.id)).size,2);await lib.toggleSaveListItem('lists:same','milk');assert.equal(book.records[0].payload.items[0].done,true);assert.equal(book.records[0].payload.items[0].custom,42);assert.deepEqual(book.records[0].payload.unknown,{keep:true});
await assert.rejects(lib.updateSave('notes:same',{body:'stale'},'old-timestamp'),/changed/);await lib.updateSave('notes:same',{body:'updated'});assert.equal(book.records[1].payload.color,3);assert.equal(book.settings.other,'keep');
failSync=true;await assert.rejects(lib.updateSave('notes:same',{title:'wrong'}),/conflict/);failSync=false;assert.notEqual(book.records[1].payload.title,'wrong');
assert.equal(lib.safeWebUrl('javascript:alert(1)'),null);await assert.rejects(lib.createSave({kind:'link',url:'data:text/html,x'}));
const journal=await lib.createEntry({body:'Private entry'});assert.equal((await lib.listEntries()).length,1);assert.equal((await lib.listSaves()).length,2);await lib.updateEntry(journal.id,{body:'Changed'});assert.equal((await lib.listEntries())[0].body,'Changed');await lib.deleteEntry(journal.id);assert.equal((await lib.listEntries()).length,0);
assert.deepEqual(lib.streakFromEntries([{entry_date:'2026-09-11'},{entry_date:'2026-09-12'},{entry_date:'2026-09-12'}],'2026-09-13'),{current:2,longest:2,total_entries:3});
book.records.push({collection:'posts',id:'post',payload:{text:'Before',privacy:'group',groupId:'group',weekPoints:25,custom:'keep'}});await lib.updatePostText({id:'post',text:'Before'},'After');assert.equal(book.records.at(-1).payload.groupId,'group');assert.equal(book.records.at(-1).payload.weekPoints,25);await lib.deletePost({id:'post'});assert.ok(!book.records.some(r=>r.collection==='posts'));const exported=await lib.buildUserExport();assert.equal(exported.calendar_events.length,1201);assert.equal(exported.daybook.settings.other,'keep');failTable=true;await assert.rejects(lib.buildUserExport(),/offline/);
const before=structuredClone(book);await assert.rejects(lib.deleteAccountAndSignOut(async()=>{throw new Error('should not sign out')}),/not available/);assert.deepEqual(book,before);
console.log('PASS: distinct collection IDs; metadata/list preservation; CAS conflict; safe links; private journal CRUD; Pacific streak; 1201-row export and fail-closed errors; non-destructive unavailable account deletion.')
}finally{await unlink(file)}
