begin;
insert into auth.users(id) values('a1111111-1111-4111-8111-111111111111'),('b2222222-2222-4222-8222-222222222222');
set local role authenticated;
do $$
declare a uuid:='a1111111-1111-4111-8111-111111111111'; b uuid:='b2222222-2222-4222-8222-222222222222'; g uuid; code text; data jsonb; rev bigint;
begin
perform set_config('request.jwt.claim.sub',a::text,true);
perform public.daybook_load();
rev:=public.daybook_sync(0,'[{"collection":"tasks","id":"private-task","payload":{"text":"Private"}}]'::jsonb,'{"profile":{"displayName":"A"}}');
if rev<>1 then raise exception 'Revision failure'; end if;
begin perform public.daybook_sync(0,'[]','{}');raise exception 'Stale save accepted';exception when serialization_failure then null;end;
begin perform public.daybook_sync(null,'[]','{}');raise exception 'NULL version accepted';exception when raise_exception then if sqlerrm='NULL version accepted' then raise;end if;end;
data:=public.daybook_group_action('create',label=>'Access test',group_kind=>'family');
g:=(data->0->>'id')::uuid;code:=data->0->>'code';
perform public.daybook_sync(1,jsonb_build_array(jsonb_build_object('collection','posts','id','shared','payload',jsonb_build_object('text','Shared','privacy','group','groupId',g))),'{"profile":{"displayName":"A"}}');
perform set_config('request.jwt.claim.sub',b::text,true);
perform public.daybook_load();
if exists(select 1 from public.daybook_records where owner_id=a) then raise exception 'Private data visible';end if;
data:=public.daybook_group_action('join',invite_code=>code);
if data->0->>'status'<>'pending' or data->0->>'code' is not null then raise exception 'Join bypassed approval';end if;
if exists(select 1 from public.daybook_records where owner_id=a) then raise exception 'Pending member read';end if;
begin perform public.daybook_group_action('approve',target=>g,member_id=>b);raise exception 'Self approval accepted';exception when insufficient_privilege then null;end;
begin insert into public.daybook_records(owner_id,collection,id,payload)values(a,'tasks','attack','{}');raise exception 'Direct write accepted';exception when insufficient_privilege then null;end;
perform set_config('request.jwt.claim.sub',a::text,true);
perform public.daybook_group_action('approve',target=>g,member_id=>b);
perform set_config('request.jwt.claim.sub',b::text,true);
if (select count(*) from public.daybook_records where owner_id=a)<>1 then raise exception 'Approved member scope incorrect';end if;
perform public.daybook_social_action('like',a,'shared');perform public.daybook_social_action('like',a,'shared');
if(select count(*) from public.daybook_reactions where post_owner=a)<>1 then raise exception 'Duplicate reaction';end if;
perform public.daybook_social_action('comment',a,'shared','Hello');
perform public.daybook_feed();
perform set_config('request.jwt.claim.sub',a::text,true);
perform public.daybook_group_action('remove',target=>g,member_id=>b);
perform set_config('request.jwt.claim.sub',b::text,true);
if exists(select 1 from public.daybook_records where owner_id=a) then raise exception 'Removed member retained access';end if;
begin perform public.daybook_social_action('comment',a,'shared','Blocked');raise exception 'Removed member commented';exception when insufficient_privilege then null;end;
end $$;
reset role;
select 'PASS: private isolation, approval, revocation, reactions, comments, write permissions and stale saves' as result;
rollback;
